version: "3.9"
services:
  auctioneer:
    build: .
    networks:
      default:
        aliases:
          - ${AUCTIONEER_NAME}
    command: npm start -- --port=${PORT} --id=${AUCTIONEER_ID}
    volumes:
      - .:/home/lokesh/Projects/ad-auction-system/${AUCTIONEER_NAME}/
      - /home/lokesh/Projects/ad-auction-system/${AUCTIONEER_NAME}/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
networks:
  default:
    name: ${BRIDGE_NETWORK_NAME}
    external: true
