version: "3.9"
services:
  bidder:
    build: .
    command: npm start -- --port=3000 --delay=195 --auctioneerURL=http://auctioneer:5000/ --id=b1
    volumes:
      - .:/home/lokesh/Projects/ad-auction-system/bidder/
      - /home/lokesh/Projects/ad-auction-system/bidder/node_modules
    ports:
      - 3000:3000
networks:
  default:
    name: myNetwork
    external: true