version: "3.9"
services:
  bidder:
    build: .
    command: npm start -- --port=${PORT} --delay=${DELAY} --auctioneerURL=${AUCTIONEER_URL} --id=${BIDDER_ID}
    volumes:
      - .:/home/lokesh/Projects/ad-auction-system/bidder/
      - /home/lokesh/Projects/ad-auction-system/bidder/node_modules
    ports:
      - ${PORT}:${PORT}
networks:
  default:
    name: ${BRIDGE_NETWORK_NAME}
    external: true